cursor #efdfe1
cursor_text_color #d5c2c5

foreground            #efdfe1
background            #191113
selection_foreground  #422931
selection_background  #e3bdc6
url_color             #ffb1c7

color0   #191113
color1   #ff7277
color2   #9eff7f
color3   #ffe272
color4   #f299b2
color5   #763346
color6   #ffb1c7
color7   #ffeff4
color8   #a5999c
color9   #ff9fa2
color10  #bbffa5
color11  #ffeca5
color12  #ffbccf
color13  #ffc8d7
color14  #ffdbe5
color15  #fff8fa
