TrackingConfigured=true
AnimeNameLanguage=english
MyAnimeListClientSecret=
TrackingRemote=anilist
MyAnimeListImported=false
SkipEd=true
PercentageToMarkComplete=85
MpvArgs=[]
Player=mpv
Provider=["allanime","animepahe"]
SubOrDub=sub
ManualProviderSearch=false
SkipFiller=true
DiscordPresence=true
MyAnimeListClientID=f76d4c827152327b60654285d221222c
TrackingLocal=true
ScoreOnCompletion=true
SubStyle=hard
SkipRecap=true
StoragePath=$HOME/.local/share/curd
MyAnimeListImportDismissed=false
ImagePreview=false
DiscordClientId=1287457464148820089
DisabledProviders=[]
AlternateScreen=true
SubsLanguage=english
RofiSelection=false
AddMissingOptions=true
NextEpisodePrompt=false
SaveMpvSpeed=true
MenuOrder=CURRENT,ALL,UNTRACKED,UPDATE,CONTINUE_LAST,TRACKER,PROVIDER
SkipOp=true
