AnimeNameLanguage=english
ManualProviderSearch=false
Player=mpv
AddMissingOptions=true
PercentageToMarkComplete=85
MyAnimeListClientID=f76d4c827152327b60654285d221222c
TrackingLocal=true
DisabledProviders=[]
SkipEd=false
MyAnimeListClientSecret=
AlternateScreen=true
NextEpisodePrompt=false
MpvArgs=[]
MyAnimeListImported=false
DiscordPresence=true
ImagePreview=false
SkipRecap=false
SubsLanguage=english
SkipFiller=false
MyAnimeListImportDismissed=false
RofiSelection=false
TrackingConfigured=true
DiscordClientId=1287457464148820089
ScoreOnCompletion=true
StoragePath=$HOME/.local/share/curd
SubOrDub=sub
SkipOp=false
Provider=stacked
SubStyle=hard
MenuOrder=CURRENT,ALL,UNTRACKED,UPDATE,CONTINUE_LAST,TRACKER,PROVIDER
SaveMpvSpeed=true
TrackingRemote=anilist
