NextEpisodePrompt=false
MenuOrder=CURRENT,ALL,UNTRACKED,UPDATE,CONTINUE_LAST,TRACKER,PROVIDER
StoragePath=$HOME/.local/share/curd
PercentageToMarkComplete=85
TrackingRemote=anilist
ScoreOnCompletion=true
MyAnimeListImportDismissed=false
AnimeNameLanguage=english
ImagePreview=false
RofiSelection=false
SkipOp=true
SkipEd=true
AlternateScreen=true
DiscordPresence=true
SkipFiller=true
Player=mpv
MyAnimeListClientSecret=
DiscordClientId=1287457464148820089
MyAnimeListClientID=f76d4c827152327b60654285d221222c
SubsLanguage=english
SkipRecap=true
AddMissingOptions=true
TrackingLocal=true
Provider=["allanime","animepahe"]
MyAnimeListImported=false
TrackingConfigured=true
SubOrDub=sub
SaveMpvSpeed=true
MpvArgs=[]
